/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_randomwalking_swt_terminal_internal_Vte */

#ifndef _Included_com_randomwalking_swt_terminal_internal_Vte
#define _Included_com_randomwalking_swt_terminal_internal_Vte
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_randomwalking_swt_terminal_internal_Vte
 * Method:    _vte_terminal_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_randomwalking_swt_terminal_internal_Vte__1vte_1terminal_1new
  (JNIEnv *, jclass);

/*
 * Class:     com_randomwalking_swt_terminal_internal_Vte
 * Method:    _vte_terminal_fork_command
 * Signature: (JLjava/lang/String;[Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;ZZZ)I
 */
JNIEXPORT jint JNICALL Java_com_randomwalking_swt_terminal_internal_Vte__1vte_1terminal_1fork_1command
  (JNIEnv *, jclass, jlong, jstring, jobjectArray, jobjectArray, jstring, jboolean, jboolean, jboolean);

/*
 * Class:     com_randomwalking_swt_terminal_internal_Vte
 * Method:    _vte_terminal_feed
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_randomwalking_swt_terminal_internal_Vte__1vte_1terminal_1feed
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_randomwalking_swt_terminal_internal_Vte
 * Method:    _vte_terminal_feed_child
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_com_randomwalking_swt_terminal_internal_Vte__1vte_1terminal_1feed_1child
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_randomwalking_swt_terminal_internal_Vte
 * Method:    _vte_terminal_set_color_foreground
 * Signature: (JLorg/eclipse/swt/internal/gtk/GdkColor;)V
 */
JNIEXPORT void JNICALL Java_com_randomwalking_swt_terminal_internal_Vte__1vte_1terminal_1set_1color_1foreground
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_randomwalking_swt_terminal_internal_Vte
 * Method:    _vte_terminal_set_color_background
 * Signature: (JLorg/eclipse/swt/internal/gtk/GdkColor;)V
 */
JNIEXPORT void JNICALL Java_com_randomwalking_swt_terminal_internal_Vte__1vte_1terminal_1set_1color_1background
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_randomwalking_swt_terminal_internal_Vte
 * Method:    _vte_terminal_reset
 * Signature: (JZZ)V
 */
JNIEXPORT void JNICALL Java_com_randomwalking_swt_terminal_internal_Vte__1vte_1terminal_1reset
  (JNIEnv *, jclass, jlong, jboolean, jboolean);

/*
 * Class:     com_randomwalking_swt_terminal_internal_Vte
 * Method:    _vte_terminal_set_scrollback_lines
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_randomwalking_swt_terminal_internal_Vte__1vte_1terminal_1set_1scrollback_1lines
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
